# Movie Recommendation System 1

In [331]:
import numpy as np 
import pandas as pd

In [332]:
df = pd.read_csv('datasets\movies.csv')

In [333]:
df.head()

Unnamed: 0                     movie  year run_time  \
0           0  The Shawshank Redemption  1994  142 min   
1           1             The Godfather  1972  175 min   
2           2           Soorarai Pottru  2020  153 min   
3           3           The Dark Knight  2008  152 min   
4           4    The Godfather: Part II  1974  202 min   

                              genre              director  \
0                 Drama                    Frank Darabont   
1          Crime  Drama              Francis Ford Coppola   
2                 Drama                     Sudha Kongara   
3  Action  Crime  Drama                 Christopher Nolan   
4          Crime  Drama              Francis Ford Coppola   

                                               about  rating  
0  Two imprisoned men bond over a number of years...     9.3  
1  An organized crime dynasty's aging patriarch t...     9.2  
2  Nedumaaran Rajangam "Maara" sets out to make t...     9.1  
3  When the menace known as the Joker wreaks havo...     9.0  
4  The early life and career of Vito Corleone in ...     9.0

In [334]:
df.shape

(1000, 8)

In [335]:
df.describe()

Unnamed: 0         year       rating
count  1000.000000  1000.000000  1000.000000
mean    499.500000  1991.211000     7.956100
std     288.819436    23.438811     0.277524
min       0.000000  1920.000000     7.600000
25%     249.750000  1976.000000     7.700000
50%     499.500000  1999.000000     7.900000
75%     749.250000  2010.000000     8.100000
max     999.000000  2021.000000     9.300000

In [336]:
df = df.rename(columns={'Unnamed: 0': 'index'})

In [337]:
df.head()

index                     movie  year run_time  \
0      0  The Shawshank Redemption  1994  142 min   
1      1             The Godfather  1972  175 min   
2      2           Soorarai Pottru  2020  153 min   
3      3           The Dark Knight  2008  152 min   
4      4    The Godfather: Part II  1974  202 min   

                              genre              director  \
0                 Drama                    Frank Darabont   
1          Crime  Drama              Francis Ford Coppola   
2                 Drama                     Sudha Kongara   
3  Action  Crime  Drama                 Christopher Nolan   
4          Crime  Drama              Francis Ford Coppola   

                                               about  rating  
0  Two imprisoned men bond over a number of years...     9.3  
1  An organized crime dynasty's aging patriarch t...     9.2  
2  Nedumaaran Rajangam "Maara" sets out to make t...     9.1  
3  When the menace known as the Joker wreaks havo...     9.0  
4  The early life and career of Vito Corleone in ...     9.0

In [338]:
df = df[['index','movie','genre','director','about']]
df.head()

index                     movie                             genre  \
0      0  The Shawshank Redemption                 Drama               
1      1             The Godfather          Crime  Drama               
2      2           Soorarai Pottru                 Drama               
3      3           The Dark Knight  Action  Crime  Drama               
4      4    The Godfather: Part II          Crime  Drama               

               director                                              about  
0        Frank Darabont  Two imprisoned men bond over a number of years...  
1  Francis Ford Coppola  An organized crime dynasty's aging patriarch t...  
2         Sudha Kongara  Nedumaaran Rajangam "Maara" sets out to make t...  
3     Christopher Nolan  When the menace known as the Joker wreaks havo...  
4  Francis Ford Coppola  The early life and career of Vito Corleone in ...

In [339]:
movieIndex = 0

In [340]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [341]:
vectorizer = TfidfVectorizer(stop_words = 'english')
features = vectorizer.fit_transform(df["about"]).todense()
features

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [342]:
print(df["about"][0])
dummy = pd.DataFrame(vectorizer.fit_transform([df["about"][0]]).todense(),columns = vectorizer.get_feature_names())
dummy

Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.


acts      bond    common   decency  eventual   finding  imprisoned  \
0  0.288675  0.288675  0.288675  0.288675  0.288675  0.288675    0.288675   

        men    number  redemption    solace     years  
0  0.288675  0.288675    0.288675  0.288675  0.288675

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [344]:
n_neighbors = 6 

def calc_KNN(df, features, movieIndex, n_neighbors):


    KNN = NearestNeighbors(n_neighbors)
    KNN.fit(features)
    
    # Use it to get neighbors
    NearestNeighbor = KNN.kneighbors(features[movieIndex], return_distance=True) 

    return NearestNeighbor

In [349]:
NearestNeighbor = calc_KNN(df, features, movieIndex, n_neighbors)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass n_neighbors=6 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [350]:
NearestNeighbor

(array([[0.        , 1.28540976, 1.32009783, 1.32736623, 1.335098  ,
         1.33628554]]),
 array([[  0, 361,  72, 182, 258, 136]], dtype=int64))

In [353]:
def printNearestNeighbor(df, NearestNeighbor, movieIndex):
    
    print("Courses similar to "+df.iloc[movieIndex]["movie"]+" are:",'\n')
    for i in range(len(NearestNeighbor[1][0])):
        if i != 0 :
            print(df.iloc[NearestNeighbor[1][0][i]])

In [354]:
printNearestNeighbor(df, NearestNeighbor, movieIndex)

Courses similar to The Shawshank Redemption are: 

index                                                     361
movie                                                   Dev.D
genre                              Drama  Romance            
director                                       Anurag Kashyap
about       After breaking up with his childhood sweethear...
Name: 361, dtype: object
index                                                      72
movie                                                  Oldboy
genre                      Action  Drama  Mystery            
director                                       Chan-wook Park
about       After being kidnapped and imprisoned for fifte...
Name: 72, dtype: object
index                                                     182
movie                                        The Great Escape
genre                   Adventure  Drama  History            
director                                         John Sturges
about       Allied prisoners of 